import { dateNow, dateStringYear } from "./date";

export const adopterInit = {
  _id: "",
  person: "NATURAL",
  type: "ADOPTER",
  name: "",
  secondName: "",
  lastName: "",
  mLastName: "",
  gender: "MAN",
  date: dateStringYear(18),
  address: "",
  document: "D.N.I.",
  documentNumber: "",
  phone: "",
  email: "",
  country: "",
  department: "",
  province: "",
  district: "",
  direction: "",
  idRegisteringEntity: 0,
  idEntity: 0,
  status: false,
};

export const petInit = {
  addressEr: "",
  userAddress: "",
  userName: "",
  adopter: "",
  adopterName: "",
  adopterLastName: "",
  dateRegistring: "",
  name: "",
  race: "",
  gender: "MALE",
  date: "",
  dateAdoption: dateNow(),
  dateIssue: dateStringYear(2, true),
  chip: "",
  chipDate: dateNow(),
  colour: "",
  image: "",
  country: "PE",
  type: "DOG",
  sterilized: "NO",
  chipFather: "",
  chipMother: "",
  pedigree: "",
};

export const petInitMethods = {
  chip: "validateString",
  gender: "validateGenderPet",
  name: "validateString",
  date: "validateDate",
  dateAdoption: "validateDate",
  type: "validateString",
  race: "validateString",
  country: "validateString",
  colour: "validateString",
  dateIssue: "validateDate",
};

export const adopterVicuInit = {
  _id: "",
  person: "NATURAL",
  type: "ADOPTER",
  name: "",
  secondName: "",
  lastName: "",
  mLastName: "",
  gender: "MAN",
  date: dateStringYear(18),
  document: "D.N.I.",
  documentNumber: "",
  phone: "",
  email: "",
  country: "",
  department: "",
  province: "",
  district: "",
  direction: "",
  idRegisteringEntity: 0,
  idEntity: 0,
  status: false,
  voucher: "",
};

// export const adopterFormRegister = {
//   country: "PE",
//   person: "NATURAL",
//   adopterType: "ADOPTER",
//   gender: "H",
//   documentType: "C.I",
//   documentNumber: "78975482",
//   email: "2017230490@untels.edu.pe",
//   addressPublic: "",
//   department: "APURÍMAC",
//   province: "ANDAHUAYLAS",
//   district: "SAN MIGUEL DE CHACCRAMPA",
//   isAddressPublic: "isAddressPublic-no",
//   dni: "78975482",
//   firstName: "romel",
//   secondName: "alexis",
//   firstLastName: "Romel",
//   secondLastName: "Alexis",
//   birthDate: "2020-02-20",
//   cellphone: "(324) 325-2352",
//   jurament1: true,
//   jurament2: true,
//   jurament3: true,
//   address: "Jr. Tarma 3048 Los ",
//   isMicrochip: "isMicrochip-no",
//   microchip: "546554576576534",
//   dateMicrochip: "2020-11-04",
//   firstNamePet: "negron",
//   specie: "DOG",
//   birthDatePet: "2015-03-20",
//   adoptionDate: "2015-02-04",
//   fatherMicrochip: "",
//   motherMicrochip: "",
//   regiterEntity: "6376a9e3a05bfe4e725d8a23",
//   countryPet: "AL",
//   genderPet: "H",
//   race: "HALF BLOOD",
//   color: "BROWN",
//   isSterilized: "isSterilized-yes",
//   fatherMicrochip: "",
//   motherMicrochip: "",
//   // isPayment: false,
//   imagePet: "",
// };

export const adopterFormRegister = {
  country: "PE",
  person: "NATURAL",
  adopterType: "ADOPTER",
  gender: "H",
  documentType: "C.I",
  documentNumber: "",
  email: "",
  addressPublic: "",
  department: "",
  province: "",
  district: "",
  isAddressPublic: "isAddressPublic-no",
  // dni: "",
  firstName: "",
  secondName: "",
  firstLastName: "",
  secondLastName: "",
  birthDate: "2015-02-20",
  cellphone: "",
  jurament1: false,
  jurament2: false,
  jurament3: false,
  address: "",
  isMicrochip: "isMicrochip-no",
  microchip: "",
  dateMicrochip: "2015-02-04",
  firstNamePet: "",
  specie: "DOG",
  birthDatePet: "2015-01-01",
  adoptionDate: "2015-02-04",
  fatherMicrochip: "",
  motherMicrochip: "",
  registerEntity: "6376a9e3a05bfe4e725d8a23",
  countryPet: "PE",
  genderPet: "H",
  race: "HALF BLOOD",
  color: "BROWN",
  isSterilized: "isSterilized-yes",
  fatherMicrochip: "",
  motherMicrochip: "",
  isPayment: false,
  imagePet: "",
};
